name: Release
on: 
    push:
        branches: 
            - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install and Fix Build Tools
        run: |
          /usr/local/lib/android/sdk/tools/bin/sdkmanager --install "build-tools;33.0.0" --sdk_root=${ANDROID_SDK_ROOT}
          cd /usr/local/lib/android/sdk/build-tools/33.0.0 && mv d8 dx &&
          cd /usr/local/lib/android/sdk/build-tools/33.0.0/lib && mv d8.jar dx.jar
      - name: Install NDK
        run: echo "y" | sudo /usr/local/lib/android/sdk/tools/bin/sdkmanager --install "ndk;23.1.7779620" --sdk_root=${ANDROID_SDK_ROOT}
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: Lint
        run: cd SmartCredentials_aOS && ./gradlew lint 
      - name: Test
        run: cd SmartCredentials_aOS && ./gradlew test
      - name: Prepare signing keys
        env:
          GPG_KEY_CONTENTS: ${{ secrets.OSSRH_GPG_SECRET_KEY_BASE64 }}
        run: |
          echo 'Create authentication module signing key'
          cd SmartCredentials_aOS/authentication
          echo $GPG_KEY_CONTENTS | base64 --decode > ./release.asc
          gpg --quiet --output ./release.gpg --dearmor ./release.asc
          echo 'Create authorization module signing key'
          cd $GITHUB_WORKSPACE/SmartCredentials_aOS/authorization
          echo $GPG_KEY_CONTENTS | base64 --decode > ./release.asc
          gpg --quiet --output ./release.gpg --dearmor ./release.asc
          echo 'Create camera module signing key'
          cd $GITHUB_WORKSPACE/SmartCredentials_aOS/camera
          echo $GPG_KEY_CONTENTS | base64 --decode > ./release.asc
          gpg --quiet --output ./release.gpg --dearmor ./release.asc
          echo 'Create core module signing key'
          cd $GITHUB_WORKSPACE/SmartCredentials_aOS/core
          echo $GPG_KEY_CONTENTS | base64 --decode > ./release.asc
          gpg --quiet --output ./release.gpg --dearmor ./release.asc
          echo 'Create documentscanner module signing key'
          cd $GITHUB_WORKSPACE/SmartCredentials_aOS/documentscanner
          echo $GPG_KEY_CONTENTS | base64 --decode > ./release.asc
          gpg --quiet --output ./release.gpg --dearmor ./release.asc
          echo 'Create eid module signing key'
          cd $GITHUB_WORKSPACE/SmartCredentials_aOS/eid
          echo $GPG_KEY_CONTENTS | base64 --decode > ./release.asc
          gpg --quiet --output ./release.gpg --dearmor ./release.asc
          echo 'Create networking module signing key'
          cd $GITHUB_WORKSPACE/SmartCredentials_aOS/networking
          echo $GPG_KEY_CONTENTS | base64 --decode > ./release.asc
          gpg --quiet --output ./release.gpg --dearmor ./release.asc
          echo 'Create otp module signing key'
          cd $GITHUB_WORKSPACE/SmartCredentials_aOS/otp
          echo $GPG_KEY_CONTENTS | base64 --decode > ./release.asc
          gpg --quiet --output ./release.gpg --dearmor ./release.asc
          echo 'Create persistentlogging module signing key'
          cd $GITHUB_WORKSPACE/SmartCredentials_aOS/persistentlogging
          echo $GPG_KEY_CONTENTS | base64 --decode > ./release.asc
          gpg --quiet --output ./release.gpg --dearmor ./release.asc
          echo 'Create pushnotifications module signing key'
          cd $GITHUB_WORKSPACE/SmartCredentials_aOS/pushnotifications
          echo $GPG_KEY_CONTENTS | base64 --decode > ./release.asc
          gpg --quiet --output ./release.gpg --dearmor ./release.asc
          echo 'Create qrlogin module signing key'
          cd $GITHUB_WORKSPACE/SmartCredentials_aOS/qrlogin
          echo $GPG_KEY_CONTENTS | base64 --decode > ./release.asc
          gpg --quiet --output ./release.gpg --dearmor ./release.asc
          echo 'Create security module signing key'
          cd $GITHUB_WORKSPACE/SmartCredentials_aOS/security
          echo $GPG_KEY_CONTENTS | base64 --decode > ./release.asc
          gpg --quiet --output ./release.gpg --dearmor ./release.asc
          echo 'Create storage module signing key'
          cd $GITHUB_WORKSPACE/SmartCredentials_aOS/storage
          echo $GPG_KEY_CONTENTS | base64 --decode > ./release.asc
          gpg --quiet --output ./release.gpg --dearmor ./release.asc 
          echo 'Create identityprovider module signing key'
          cd $GITHUB_WORKSPACE/SmartCredentials_aOS/identityprovider
          echo $GPG_KEY_CONTENTS | base64 --decode > ./release.asc
          gpg --quiet --output ./release.gpg --dearmor ./release.asc
      - name: Assemble all subproject aar files
        run: cd SmartCredentials_aOS && ./gradlew assembleRelease
        env:
          OSSRH_GPG_SECRET_KEY_ID: ${{ secrets.OSSRH_GPG_SECRET_KEY_ID }}
          OSSRH_GPG_SECRET_KEY_BASE64: ${{ secrets.OSSRH_GPG_SECRET_KEY_BASE64 }}
          OSSRH_GPG_SECRET_KEY_RING_FILE: ${{ secrets.OSSRH_GPG_SECRET_KEY_RING_FILE }}
          OSSRH_GPG_SECRET_KEY_PASSWORD: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}        
      - name: Upload Authentication AAR
        uses: actions/upload-artifact@v2
        with:
            name: authentication
            path: SmartCredentials_aOS/authentication/build/outputs/aar/        
      - name: Upload Authorization AAR
        uses: actions/upload-artifact@v2
        with:
            name: authorization
            path: SmartCredentials_aOS/authorization/build/outputs/aar/
      - name: Upload Camera AAR
        uses: actions/upload-artifact@v2
        with:
            name: camera
            path: SmartCredentials_aOS/camera/build/outputs/aar/
      - name: Upload Core AAR
        uses: actions/upload-artifact@v2
        with:
            name: core
            path: SmartCredentials_aOS/core/build/outputs/aar/               
      - name: Upload Document Scanner AAR
        uses: actions/upload-artifact@v2
        with:
            name: documentscanner
            path: SmartCredentials_aOS/documentscanner/build/outputs/aar/
      - name: Upload eID AAR
        uses: actions/upload-artifact@v2
        with:
            name: eid
            path: SmartCredentials_aOS/eid/build/outputs/aar/     
      - name: Upload Networking AAR
        uses: actions/upload-artifact@v2
        with:
            name: networking
            path: SmartCredentials_aOS/networking/build/outputs/aar/
      - name: Upload OTP AAR
        uses: actions/upload-artifact@v2
        with:
            name: otp
            path: SmartCredentials_aOS/otp/build/outputs/aar/          
      - name: Upload Persistent Logging AAR
        uses: actions/upload-artifact@v2
        with:
            name: persistentlogging
            path: SmartCredentials_aOS/persistentlogging/build/outputs/aar/              
      - name: Upload Push Notifications AAR
        uses: actions/upload-artifact@v2
        with:
            name: pushnotifications
            path: SmartCredentials_aOS/pushnotifications/build/outputs/aar/     
      - name: Upload QR Login AAR
        uses: actions/upload-artifact@v2
        with:
            name: qrlogin
            path: SmartCredentials_aOS/qrlogin/build/outputs/aar/                
      - name: Upload Security AAR
        uses: actions/upload-artifact@v2
        with:
            name: security
            path: SmartCredentials_aOS/security/build/outputs/aar/            
      - name: Upload Storage AAR
        uses: actions/upload-artifact@v2
        with:
            name: storage
            path: SmartCredentials_aOS/storage/build/outputs/aar/ 
      - name: Upload Identity Provider AAR
        uses: actions/upload-artifact@v2
        with:
            name: identityprovider
            path: SmartCredentials_aOS/identityprovider/build/outputs/aar/ 
      - name: Sonatype Upload
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          OSSRH_GPG_SECRET_KEY_ID: ${{ secrets.OSSRH_GPG_SECRET_KEY_ID }}
          OSSRH_GPG_SECRET_KEY_RING_FILE: ${{ secrets.OSSRH_GPG_SECRET_KEY_RING_FILE }}
          OSSRH_GPG_SECRET_KEY_PASSWORD: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
        run: cd SmartCredentials_aOS && ./gradlew publish       
